name = "SrcMD"
uuid = "e1a0bd64-771e-4a39-a34b-9982bd4fbbe2"
version = "1.0.0-DEV"
authors = ["Brian D. Klahn <briandk@klahpages.net> and contributors"]

[deps]
FileTrees = "72696420-646e-6120-6e77-6f6420746567"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"

[compat]
FileTrees = "0.3.10"
Mustache = "1.0.21"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
