name = "SrcMD"
uuid = "e1a0bd64-771e-4a39-a34b-9982bd4fbbe2"
authors = ["Brian D. Klahn <briandk@klahpages.net> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
