name = "SrcMD"
uuid = "e1a0bd64-771e-4a39-a34b-9982bd4fbbe2"
version = "1.0.0-DEV"
authors = ["Brian D. Klahn <briandk@klahpages.net> and contributors"]

[deps]
BaseDirs = "18cc8868-cbac-4acf-b575-c8ff214dc66f"
FileTrees = "72696420-646e-6120-6e77-6f6420746567"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
BaseDirs = "1.3.2"
FileTrees = "0.3.10"
HTTP = "1.10.19"
JSON3 = "1.14.3"
Mustache = "1.0.21"
TOML = "1.0.3"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
